resource.AddFile("materials/jessev92/bf2/parachute_c.vmt")
resource.AddFile("materials/jessev92/bf2/parachute_c.vtf")
resource.AddFile("materials/jessev92/bf2/parachute_n.vtf")

resource.AddFile("models/jesev92/bf2/parachute.dx80.vtx")
resource.AddFile("models/jesev92/bf2/parachute.dx90.vtx")
resource.AddFile("models/jesev92/bf2/parachute.mdl")
resource.AddFile("models/jesev92/bf2/parachute.phy")
resource.AddFile("models/jesev92/bf2/parachute.sw.vtx")
resource.AddFile("models/jesev92/bf2/parachute.vvd")